### ISSUE TITLE
Bug causing server keep crashing

### ISSUE THREAD

**Issue by kit8379** [nulli0n/NexEngine#10]
[14:09:44 ERROR]: Packet encoding of packet ID 34 threw (skippable? false)
io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException: encoded string (rO0ABXNy...XEAfgAR
) too long: 491564 bytes
        at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:426) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeCollection(FriendlyByteBuf.java:134) ~[?:?]
        at net.minecraft.network.protocol.game.ClientboundLevelChunkPacket.write(ClientboundLevelChunkPacket.java:130) ~[?:?]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:44) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.network.PacketEncoder.encode(PacketEncoder.java:15) ~[patched_1.17.jar:git-Purpur-1240]
        at jdk.internal.reflect.GeneratedMethodAccessor664.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.encode(ChannelInjector.java:528) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$100(ChannelInjector.java:70) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.encode(ChannelInjector.java:268) ~[?:?]
        at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[patched_1.17.jar:git-Purpur-1240]
        at com.comphenix.protocol.injector.netty.ChannelInjector$1.write(ChannelInjector.java:274) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:115) ~[patched_1.17.jar:git-Purpur-1240]
        at su.nexmedia.engine.nms.packets.PacketManager$1.write(PacketManager.java:112) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[patched_1.17.jar:git-Purpur-1240]
        at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327) ~[?:?]
        at net.minecraft.network.Connection.a(Connection.java:450) ~[?:?]
        at net.minecraft.network.Connection.lambda$writePacket$8(Connection.java:424) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:351) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.jar:git-Purpur-1240]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.jar:git-Purpur-1240]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.UTFDataFormatException: encoded string (rO0ABXNy...XEAfgAR
) too long: 491564 bytes
        at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:?]
        at java.io.DataOutputStream.writeUTF(Unknown Source) ~[?:?]
        at io.netty.buffer.ByteBufOutputStream.writeUTF(ByteBufOutputStream.java:143) ~[patched_1.17.jar:git-Purpur-1240]
        at net.minecraft.nbt.StringTag.write(StringTag.java:65) ~[?:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:422) ~[?:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:77) ~[?:?]
        at net.minecraft.nbt.CompoundTag.writeNamedTag(CompoundTag.java:422) ~[?:?]
        at net.minecraft.nbt.CompoundTag.write(CompoundTag.java:77) ~[?:?]
        at net.minecraft.nbt.NbtIo.writeUnnamedTag(NbtIo.java:206) ~[?:?]
        at net.minecraft.nbt.NbtIo.write(NbtIo.java:199) ~[?:?]
        at net.minecraft.network.FriendlyByteBuf.writeNbt(FriendlyByteBuf.java:424) ~[?:?]
        ... 35 more

**Comment by kit8379** [comment]
I think it is not related since I removed it and error keep occurs. Sorry for annoying.
