### ISSUE TITLE
Weird mistake ??

### ISSUE THREAD

**Issue by MrFidelon1** [nulli0n/NexEngine#2]
I got this error when I tp a friend (my pc was a bit slow at the time)

[03:50:47 ERROR]: Could not pass event PlayerQuitEvent to NexEngine v2.0.4.1
java.util.NoSuchElementException: nex_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[patched_1.16.5.jar:git-Yatopia-17]
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[patched_1.16.5.jar:git-Yatopia-17]
        at com.comphenix.protocol.injector.netty.PipelineProxy.remove(PipelineProxy.java:318) ~[?:?]
        at su.nexmedia.engine.nms.packets.PacketManager.removePlayer(PacketManager.java:77) ~[?:?]
        at su.nexmedia.engine.nms.packets.PacketManager.onQuit(PacketManager.java:129) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-17]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Yatopia-17]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-17]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:525) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1782) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:332) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:184) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:540) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:150) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1469) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:397) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1288) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1013) ~[patched_1.16.5.jar:git-Yatopia-17]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Yatopia-17]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by andris155** [comment]
I have same problem if player kicked.
```
[13:12:35] [Server thread/INFO]: MrZeri issued server command: /kick WolterFox
[13:12:35] [Server thread/INFO]: WolterFox lost connection: Kidobtak a szerverről.
[13:12:35] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to NexEngine v2.0.6
java.util.NoSuchElementException: nex_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at com.comphenix.protocol.injector.netty.PipelineProxy.remove(PipelineProxy.java:313) ~[?:?]
	at su.nexmedia.engine.nms.packets.PacketManager.removePlayer(PacketManager.java:77) ~[?:?]
	at su.nexmedia.engine.nms.packets.PacketManager.onQuit(PacketManager.java:129) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor32.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1910) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:459) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.disconnect(PlayerConnection.java:426) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at org.bukkit.craftbukkit.v1_16_R3.entity.CraftPlayer.kickPlayer(CraftPlayer.java:502) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at com.earth2me.essentials.commands.Commandkick.run(Commandkick.java:51) ~[?:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:202) ~[?:?]
	at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:197) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:705) ~[?:?]
	at com.earth2me.essentials.Essentials.onCommand(Essentials.java:612) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2238) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2053) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2006) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1311) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1304) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1280) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1124) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Tuinity-"1b0d783"]
	at java.lang.Thread.run(Unknown Source) [?:?]
[13:12:35] [Server thread/INFO]: [-] WolterFox
```
